version: 2.1

jobs:
  sayhello:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello World!"
      - run : echo "Hello Marie-Pier" 
  displayfiles:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "la -al"

workflows:
  monWorkflow:
    jobs:
      - sayhello
      - displayfiles:
          requires:
          - sayhello
