version: 2.1

jobs:
  checkout_and_unit_test:
    description: A job that checkout and tests
    machine: true
    steps:
      - run: echo "Hello World!"
  deploy_backend:
    description: A job that deploys_backend
    machine: true
    steps:
      - run: echo "Hello World!"
  integration_tests_backend:
    description: A job that integrates tests to backend
    machine: true
    steps:
      - run: echo "allo"
  deploy_staging:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  acceptence_tests_4:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  acceptence_tests_3:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  acceptence_tests_2:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  acceptence_tests_1:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  deploy_production:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: echo "allo"
  
workflows:
  monWorkflow:
    jobs:
      - checkout_and_unit_test
      - deploy_backend
      - integration_tests_backend
      - deploy_staging
      - acceptence_tests_4:
          requires:
            - deploy_staging
      - acceptence_tests_3:
          requires:
          - deploy_staging
      - acceptence_tests_2:
          requires:
          - deploy_staging
      - acceptence_tests_1:
          requires:
          - deploy_staging
      - deploy_production
